spring.application.name=auth-service
server.port=8083

# POSTGRES
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/delivery_auth_db
spring.datasource.username=${AUTH_DB_USER}
spring.datasource.password=${AUTH_DB_PASSWORD}

# REDIS
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# KAFKA
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}

# OTHER
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
